jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC"
  numExecutors: 2
  mode: NORMAL

  securityRealm:
    local:
      users:
        - id: admin
          password: 123456

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true

  tools:
    git:
      installations:
        - name: "Default"
          home: "/usr/bin/git"

  # jobs:
  #   - script: >
  #       pipelineJob('example-pipeline') {
  #         definition {
  #           cps {
  #             script('pipeline { agent any; stages { stage("Hello") { steps { echo "Hello, World!" } } } }')
  #             sandbox()
  #           }
  #         }
  #       }

  plugins:
    required:
      - configuration-as-code
      - git
#      - workflow-aggregator

